version: '3'

services:
    app:
        build: .
        container_name: micro-videos-typescript-app
        command: .docker/start.sh
        volumes:
            - .:/home/node/app
        ports:
            - 8889:8889
